resources:
  - url: http://127.0.0.1:5000/plant-humidity-card.js
    type: module
views:
  - cards:
      - type: custom:plant-humidity-card
        name: PlantHumidity Card Development
        entity: sun.sun
        test_gui: true
